@testset "Algorithms -> Real root classification" begin
    R, (a, b, c) = polynomial_ring(QQ, [:a, :b, :c])
    R′, (x,) = polynomial_ring(fraction_field(R), [:x], internal_ordering=:degrevlex)
    f = ParametricIdeal([a * x^2 + b * x + c])
    # Mathematically, the set of (a,b,c) in R^3 such that
    # a*x^2+b*x+c has a real root satisfying a*x+c > 0
    # is given by (a != 0) and (b^2-4ac != 0) and (2c-b > 0 or c(b-a-c) > 0)
    rrc = AlgebraicSolving.real_root_classification(f, [a * x + c])
    ineqs = rrc.S[1].ineqs
    polys = unique([q for p in rrc.S[2].polys for (q, _) in factor(p)])
    # We verify that the polynomials in the semi-algebraic description
    # appear in the expected set of polynomials
    @test a in ineqs
    @test 4*a*c-b^2 in ineqs
    @test b-2*c in polys
    @test a-b+c in polys
end

@testset "Algorithms -> Real root classification 2" begin
    R, (a,) = polynomial_ring(QQ, [:a])
    R′, (x,) = polynomial_ring(fraction_field(R), [:x], internal_ordering=:degrevlex)
    f = ParametricIdeal([x^2 - x, x^2 - (a + 1) * x + a])
    rrc = AlgebraicSolving.real_root_classification(f, [1-2*x])
    # When a = 1, the ideal is generated by x^2-x instead of x-1, so x = 0 is such that 1-2*x > 0.
    # In other words, evaluate(rrc, [QQ(1)]) should be true, which is not the case.
    # This is why the real root classification is only guaranteed to be correct generically.
    @test !evaluate(rrc, [QQ(1)])
end
