export eco

@doc Markdown.doc"""
    eco(n::Int)

Given a positive natural number `n` returns the Eco ideal generated by
$(x_k + \sum_{j=1}^{n-k-1} x_j x_{j+k})x_n - k$ for $k \in \{1, \ldots, n-1\}$
and $1 + \sum_{j=1}^{n-1} x_j$. For `n = 1`, this is the unit ideal.

# Example
```jldoctest
julia> using AlgebraicSolving

julia> eco(3)
QQMPolyRingElem[x1*x2*x3 + x1*x3 - 1, x2*x3 - 2, x1 + x2 + 1]
```
"""
function eco(n::Int, characteristic::Int=0)
    n >= 1 || throw(ArgumentError("Eco systems require at least one variable."))

    if characteristic == 0
        R, _ = polynomial_ring(QQ, n, internal_ordering=:degrevlex)
    elseif is_probable_prime(characteristic)
        R, _ = polynomial_ring(GF(characteristic), n, internal_ordering=:degrevlex)
    else
        error("We only support finite fields or QQ as ground fields.")
    end

    return eco(R)
end

@doc Markdown.doc"""
    eco(R::MPolyRing)

Returns the Eco ideal in the given polynomial ring `R`, which must have at least one variable.

# Example
```jldoctest
julia> using AlgebraicSolving

julia> R, _ = QQ["x", "y", "z"]
(Multivariate polynomial ring in 3 variables over QQ, QQMPolyRingElem[x, y, z])

julia> eco(R)
QQMPolyRingElem[x*y*z + x*z - 1, y*z - 2, x + y + 1]
```
"""
function eco(R::MPolyRing)
    CR = base_ring(R)
    vars = gens(R)
    polys = elem_type(R)[]
    n = nvars(R)
    n >= 1 || throw(ArgumentError("Eco systems require at least one variable."))

    for k in 1:(n-1)
        polynomial = vars[k]
        for j in 1:(n-k-1)
            polynomial += vars[j] * vars[j+k]
        end
        polynomial *= vars[n]
        polynomial -= CR(k)
        push!(polys, polynomial)
    end

    linear_poly = R(1)
    for k in 1:(n-1)
        linear_poly += vars[k]
    end
    push!(polys, linear_poly)

    return Ideal(polys)
end
