using Markdown
using Test
using msolve_jll
using AbstractAlgebra
using Nemo
using LinearAlgebra

import AbstractAlgebra:
    @attr,
    @attributes,
    @show_name,
    @show_special,
    addeq!,
    base_ring,
    canonical_unit,
    codomain,
    characteristic,
    data,
    degree,
    dim,
    domain,
    elem_type,
    evaluate,
    expressify,
    Field,
    FieldElem,
    force_coerce,
    force_op,
    gen,
    Generic,
    Generic.finish,
    Generic.MPolyBuildCtx,
    Generic.MPolyCoeffs,
    Generic.MPolyExponentVectors,
    Generic.push_term!,
    gens,
    get_attribute,
    get_attribute!,
    GF,
    Ideal,
    Map,
    map,
    MatElem,
    matrix,
    MatSpace,
    MPolyElem,
    MPolyRing,
    NCRing,
    NCRingElem,
    ngens,
    nvars,
    ordering,
    parent_type,
    PolyElem,
    PolynomialRing,
    PolyRing,
    Ring,
    RingElem,
    RingElement,
    set_attribute!,
    SetMap,
    symbols,
    total_degree

import Nemo:
    bell,
    binomial,
    denominator,
    divexact,
    divides,
    divisor_sigma,
    euler_phi,
    factorial,
    fibonacci,
    fits,
    FlintIntegerRing,
    FlintRationalField,
    fmpq,
    fmpq_mat,
    fmpz,
    fmpz_mat,
    fq_nmod,
    FractionField,
    height,
    is_prime,
    is_probable_prime,
    is_square,
    is_unit,
    isqrtrem,
    jacobi_symbol,
    MatrixSpace,
    moebius_mu,
    number_of_partitions,
    numerator,
    primorial,
    QQ,
    rising_factorial,
    root,
    unit,
    ZZ
